import type { ActivityEvent, AffiliateApplication, FraudSignal, PayoutRule, ProgramAnalytics, ProgramTier } from "./types";

export const demoAnalytics: ProgramAnalytics = {
  applicationVolume: 128,
  approvalRate: 42,
  medianReviewHours: 6.8,
  projectedMonthlyRevenue: 184000,
  flaggedApplications: 17,
  payoutExposure: 62000,
  activePartners: 312,
  autoReviewCoverage: 76,
};

export const demoApplications: AffiliateApplication[] = [
  {
    id: "app_1001",
    companyName: "Northstar Review Lab",
    contactName: "Maya Chen",
    channel: "content",
    status: "approved",
    country: "US",
    audienceSize: 185000,
    monthlyTraffic: 92000,
    verticalFitScore: 94,
    qualityScore: 91,
    fraudRiskScore: 8,
    expectedMonthlyRevenue: 28000,
    requestedCommissionRate: 18,
    approvedCommissionRate: 16,
    submittedAt: "2026-05-28T10:30:00Z",
    reviewer: "Ari Patel",
    notes: "Strong buying intent content with clear disclosure placement and clean backlink history.",
    evidence: ["Organic review pages", "FTC disclosure screenshot", "Traffic sample"],
    riskFlags: [],
  },
  {
    id: "app_1002",
    companyName: "Promo Harbor",
    contactName: "Jonas Meyer",
    channel: "coupon",
    status: "reviewing",
    country: "DE",
    audienceSize: 240000,
    monthlyTraffic: 150000,
    verticalFitScore: 72,
    qualityScore: 63,
    fraudRiskScore: 48,
    expectedMonthlyRevenue: 21000,
    requestedCommissionRate: 22,
    submittedAt: "2026-05-29T08:15:00Z",
    reviewer: "Leah Stone",
    notes: "High traffic coupon site with possible trademark bidding overlap and unclear placement rules.",
    evidence: ["Coupon landing page", "Search ad screenshots", "Domain ownership record"],
    riskFlags: ["Trademark overlap", "High incentive traffic"],
  },
  {
    id: "app_1003",
    companyName: "BuilderOps Weekly",
    contactName: "Renee Walton",
    channel: "newsletter",
    status: "approved",
    country: "CA",
    audienceSize: 67000,
    monthlyTraffic: 38000,
    verticalFitScore: 88,
    qualityScore: 86,
    fraudRiskScore: 12,
    expectedMonthlyRevenue: 17500,
    requestedCommissionRate: 15,
    approvedCommissionRate: 14,
    submittedAt: "2026-05-30T13:20:00Z",
    reviewer: "Ari Patel",
    notes: "Niche B2B list with verified subscribers and transparent sponsored content policy.",
    evidence: ["Subscriber analytics", "Sample issue", "Sponsorship policy"],
    riskFlags: [],
  },
  {
    id: "app_1004",
    companyName: "Apex Scale Partners",
    contactName: "Nico Alvarez",
    channel: "paid_search",
    status: "needs_info",
    country: "US",
    audienceSize: 112000,
    monthlyTraffic: 45000,
    verticalFitScore: 79,
    qualityScore: 70,
    fraudRiskScore: 37,
    expectedMonthlyRevenue: 33000,
    requestedCommissionRate: 24,
    submittedAt: "2026-05-31T16:05:00Z",
    reviewer: "Mina Howard",
    notes: "Revenue potential is high, but keyword policy and landing page ownership need confirmation.",
    evidence: ["Ad account export", "Landing page list"],
    riskFlags: ["Missing keyword exclusions"],
  },
  {
    id: "app_1005",
    companyName: "Creator Cart Studio",
    contactName: "Priya Raman",
    channel: "influencer",
    status: "approved",
    country: "GB",
    audienceSize: 410000,
    monthlyTraffic: 88000,
    verticalFitScore: 82,
    qualityScore: 84,
    fraudRiskScore: 18,
    expectedMonthlyRevenue: 24000,
    requestedCommissionRate: 20,
    approvedCommissionRate: 17,
    submittedAt: "2026-06-01T09:45:00Z",
    reviewer: "Leah Stone",
    notes: "Strong creator fit with clean engagement ratio and repeatable launch calendar.",
    evidence: ["Audience demographics", "Engagement audit", "Disclosure sample"],
    riskFlags: [],
  },
  {
    id: "app_1006",
    companyName: "Signal Bridge Consulting",
    contactName: "Theo Morris",
    channel: "b2b",
    status: "reviewing",
    country: "AU",
    audienceSize: 24000,
    monthlyTraffic: 12000,
    verticalFitScore: 91,
    qualityScore: 89,
    fraudRiskScore: 10,
    expectedMonthlyRevenue: 19000,
    requestedCommissionRate: 16,
    submittedAt: "2026-06-02T11:10:00Z",
    reviewer: "Mina Howard",
    notes: "Smaller audience but excellent buyer concentration and account based referral motion.",
    evidence: ["Client list sample", "Referral workflow", "Case study outline"],
    riskFlags: [],
  },
  {
    id: "app_1007",
    companyName: "ClickForge Media",
    contactName: "Sam Kline",
    channel: "paid_search",
    status: "rejected",
    country: "US",
    audienceSize: 540000,
    monthlyTraffic: 300000,
    verticalFitScore: 51,
    qualityScore: 42,
    fraudRiskScore: 86,
    expectedMonthlyRevenue: 45000,
    requestedCommissionRate: 30,
    submittedAt: "2026-06-03T12:00:00Z",
    reviewer: "Ari Patel",
    notes: "Blocked for domain spoofing indicators and unverifiable traffic sources.",
    evidence: ["Traffic spike report", "WHOIS mismatch", "Ad copy sample"],
    riskFlags: ["Domain mismatch", "Traffic anomaly", "Policy conflict"],
  },
  {
    id: "app_1008",
    companyName: "Founder Tools Digest",
    contactName: "Iris Okafor",
    channel: "newsletter",
    status: "approved",
    country: "US",
    audienceSize: 98000,
    monthlyTraffic: 51000,
    verticalFitScore: 90,
    qualityScore: 88,
    fraudRiskScore: 9,
    expectedMonthlyRevenue: 26000,
    requestedCommissionRate: 17,
    approvedCommissionRate: 16,
    submittedAt: "2026-06-04T14:35:00Z",
    reviewer: "Leah Stone",
    notes: "High intent founder audience with mature sponsorship operations and verified list health.",
    evidence: ["List health report", "Sponsorship calendar", "Audience survey"],
    riskFlags: [],
  },
  {
    id: "app_1009",
    companyName: "CloudStack Tutorials",
    contactName: "Owen Brooks",
    channel: "content",
    status: "new",
    country: "IE",
    audienceSize: 72000,
    monthlyTraffic: 66000,
    verticalFitScore: 85,
    qualityScore: 81,
    fraudRiskScore: 15,
    expectedMonthlyRevenue: 14500,
    requestedCommissionRate: 15,
    submittedAt: "2026-06-05T09:00:00Z",
    reviewer: "Unassigned",
    notes: "Technical tutorial site awaiting automated evidence extraction and reviewer assignment.",
    evidence: ["Tutorial index", "Analytics screenshot"],
    riskFlags: [],
  },
  {
    id: "app_1010",
    companyName: "ValuePerk Network",
    contactName: "Elena Novak",
    channel: "coupon",
    status: "paused",
    country: "PL",
    audienceSize: 305000,
    monthlyTraffic: 170000,
    verticalFitScore: 64,
    qualityScore: 58,
    fraudRiskScore: 59,
    expectedMonthlyRevenue: 16000,
    requestedCommissionRate: 25,
    submittedAt: "2026-06-05T15:20:00Z",
    reviewer: "Mina Howard",
    notes: "Paused until source of discount inventory and browser extension behavior are documented.",
    evidence: ["Extension listing", "Coupon feed sample"],
    riskFlags: ["Extension attribution risk", "Missing consent language"],
  },
  {
    id: "app_1011",
    companyName: "AutoCompare Guides",
    contactName: "Nadia Reeves",
    channel: "content",
    status: "needs_info",
    country: "US",
    audienceSize: 128000,
    monthlyTraffic: 76000,
    verticalFitScore: 83,
    qualityScore: 74,
    fraudRiskScore: 34,
    expectedMonthlyRevenue: 20500,
    requestedCommissionRate: 19,
    submittedAt: "2026-06-06T10:40:00Z",
    reviewer: "Compliance bot",
    notes: "AI-generated comparison pages look commercially relevant, but disclosure placement and substantiation for product claims need verification before approval.",
    evidence: ["AI content sample", "Disclosure placement crawl", "Claim substantiation checklist"],
    riskFlags: ["Missing affiliate disclosure", "AI content labeling review"],
  },
];

export const demoTiers: ProgramTier[] = [
  { id: "tier_1", name: "Verified Content", commissionRate: 14, minQualityScore: 80, minMonthlyRevenue: 10000, cookieWindowDays: 45, payoutHoldDays: 14, partnerCount: 128, complianceRule: "Disclosure and content ownership verified" },
  { id: "tier_2", name: "Strategic Growth", commissionRate: 18, minQualityScore: 86, minMonthlyRevenue: 20000, cookieWindowDays: 60, payoutHoldDays: 21, partnerCount: 44, complianceRule: "Monthly incrementality review required" },
  { id: "tier_3", name: "Managed Paid Media", commissionRate: 12, minQualityScore: 75, minMonthlyRevenue: 15000, cookieWindowDays: 30, payoutHoldDays: 30, partnerCount: 31, complianceRule: "Keyword exclusions and ad copy approval required" },
  { id: "tier_4", name: "Watchlist Coupon", commissionRate: 8, minQualityScore: 60, minMonthlyRevenue: 5000, cookieWindowDays: 7, payoutHoldDays: 45, partnerCount: 22, complianceRule: "No toolbar injection, no trademark bidding, manual payout review" },
];

export const demoFraudSignals: FraudSignal[] = [
  { id: "sig_1", applicationId: "app_1002", label: "Trademark bidding overlap", severity: "medium", confidence: 82, description: "Ad screenshots include protected brand variants without clear exclusion rules.", recommendedAction: "Request keyword negative list before approval." },
  { id: "sig_2", applicationId: "app_1007", label: "Domain ownership mismatch", severity: "high", confidence: 94, description: "Submitted traffic source points to a domain not controlled by the applicant.", recommendedAction: "Reject and block related domains." },
  { id: "sig_3", applicationId: "app_1007", label: "Traffic anomaly", severity: "high", confidence: 89, description: "Traffic increased 9x within 48 hours before application with no matching content event.", recommendedAction: "Reject pending verifiable analytics export." },
  { id: "sig_4", applicationId: "app_1010", label: "Extension attribution risk", severity: "medium", confidence: 78, description: "Browser extension may overwrite checkout attribution after demand is already created.", recommendedAction: "Pause and require consent language plus click path recording." },
  { id: "sig_5", applicationId: "app_1004", label: "Missing keyword exclusions", severity: "low", confidence: 66, description: "Paid search partner has not supplied negative keyword controls.", recommendedAction: "Hold approval until policy pack is uploaded." },
  { id: "sig_6", applicationId: "app_1011", label: "Disclosure and AI content review", severity: "medium", confidence: 84, description: "Crawl found comparison pages with affiliate calls to action but inconsistent disclosure placement and unlabeled AI-assisted copy.", recommendedAction: "Request disclosure screenshots, AI content labeling policy, and claim substantiation before tier assignment." },
];

export const demoPayoutRules: PayoutRule[] = [
  { id: "rule_1", name: "First order validation", condition: "New customer order is not refunded after 14 days", action: "Release standard commission", protectsAgainst: "Refund abuse", active: true },
  { id: "rule_2", name: "Coupon watchlist hold", condition: "Partner channel is coupon and fraud risk score is over 45", action: "Hold payout for manual incrementality review", protectsAgainst: "Low incrementality attribution", active: true },
  { id: "rule_3", name: "Paid search policy lock", condition: "Missing negative keyword evidence", action: "Prevent approval and assign compliance task", protectsAgainst: "Trademark bidding", active: true },
  { id: "rule_4", name: "High value partner fast lane", condition: "Quality score over 86 and fraud risk under 15", action: "Auto assign strategic tier recommendation", protectsAgainst: "Slow onboarding of high fit partners", active: true },
  { id: "rule_5", name: "Dormant source review", condition: "No tracked clicks for 30 days after approval", action: "Move partner to reactivation queue", protectsAgainst: "Inactive program bloat", active: false },
];

export const demoActivity: ActivityEvent[] = [
  { id: "evt_1", timestamp: "09:12", actor: "AI reviewer", type: "ai_review", message: "Scored CloudStack Tutorials at 85 fit with no active fraud flags." },
  { id: "evt_2", timestamp: "09:38", actor: "Leah Stone", type: "approval", message: "Approved Founder Tools Digest into Verified Content tier at 16 percent commission." },
  { id: "evt_3", timestamp: "10:04", actor: "Compliance bot", type: "compliance", message: "Paused ValuePerk Network until extension consent proof is uploaded." },
  { id: "evt_4", timestamp: "10:31", actor: "Payout rules", type: "payout", message: "Applied 45 day hold to coupon partner applications with medium risk signals." },
  { id: "evt_5", timestamp: "11:16", actor: "Ari Patel", type: "manual_review", message: "Rejected ClickForge Media after domain ownership mismatch review." },
  { id: "evt_6", timestamp: "11:45", actor: "AI reviewer", type: "ai_review", message: "Recommended Signal Bridge Consulting for strategic review despite lower traffic volume." },
];
